import type { KeyboardLayout } from '../types';

export const nordicLayout: KeyboardLayout = {
  id: 'nordic',
  label: 'Combined Nordic',
  rows: [
    [
      { code: 'Backquote', label: '§', insertText: '§' },
      { code: 'Digit1', label: '1', insertText: '1' },
      { code: 'Digit2', label: '2', insertText: '2' },
      { code: 'Digit3', label: '3', insertText: '3' },
      { code: 'Digit4', label: '4', insertText: '4' },
      { code: 'Digit5', label: '5', insertText: '5' },
      { code: 'Digit6', label: '6', insertText: '6' },
      { code: 'Digit7', label: '7', insertText: '7' },
      { code: 'Digit8', label: '8', insertText: '8' },
      { code: 'Digit9', label: '9', insertText: '9' },
      { code: 'Digit0', label: '0', insertText: '0' },
      { code: 'Minus', label: '+', insertText: '+' },
      { code: 'Equal', label: '´', insertText: '´' },
      { code: 'Backspace', label: 'Backspace', width: 1.8 },
    ],
    [
      { code: 'Tab', label: 'Tab', insertText: '\t', width: 1.5 },
      { code: 'KeyQ', label: 'Q', insertText: 'q' },
      { code: 'KeyW', label: 'W', insertText: 'w' },
      { code: 'KeyE', label: 'E', insertText: 'e' },
      { code: 'KeyR', label: 'R', insertText: 'r' },
      { code: 'KeyT', label: 'T', insertText: 't' },
      { code: 'KeyY', label: 'Y', insertText: 'y' },
      { code: 'KeyU', label: 'U', insertText: 'u' },
      { code: 'KeyI', label: 'I', insertText: 'i' },
      { code: 'KeyO', label: 'O', insertText: 'o' },
      { code: 'KeyP', label: 'P', insertText: 'p' },
      { code: 'BracketLeft', label: 'Å', insertText: 'å' },
      { code: 'BracketRight', label: 'Ä', insertText: 'ä' },
      { code: 'Backslash', label: 'Ö', insertText: 'ö' },
    ],
    [
      { code: 'CapsLock', label: 'Caps', width: 1.8 },
      { code: 'KeyA', label: 'A', insertText: 'a' },
      { code: 'KeyS', label: 'S', insertText: 's' },
      { code: 'KeyD', label: 'D', insertText: 'd' },
      { code: 'KeyF', label: 'F', insertText: 'f' },
      { code: 'KeyG', label: 'G', insertText: 'g' },
      { code: 'KeyH', label: 'H', insertText: 'h' },
      { code: 'KeyJ', label: 'J', insertText: 'j' },
      { code: 'KeyK', label: 'K', insertText: 'k' },
      { code: 'KeyL', label: 'L', insertText: 'l' },
      { code: 'Semicolon', label: 'Æ', insertText: 'æ' },
      { code: 'Quote', label: 'Ø', insertText: 'ø' },
      { code: 'Enter', label: 'Enter', insertText: '\n', width: 1.8 },
    ],
    [
      { code: 'ShiftLeft', label: 'Shift', width: 2.2 },
      { code: 'KeyZ', label: 'Z', insertText: 'z' },
      { code: 'KeyX', label: 'X', insertText: 'x' },
      { code: 'KeyC', label: 'C', insertText: 'c' },
      { code: 'KeyV', label: 'V', insertText: 'v' },
      { code: 'KeyB', label: 'B', insertText: 'b' },
      { code: 'KeyN', label: 'N', insertText: 'n' },
      { code: 'KeyM', label: 'M', insertText: 'm' },
      { code: 'Comma', label: ',', insertText: ',' },
      { code: 'Period', label: '.', insertText: '.' },
      { code: 'Slash', label: '-', insertText: '-' },
      { code: 'ShiftRight', label: 'Shift', width: 2.2 },
    ],
    [
      { code: 'ControlLeft', label: 'Ctrl', width: 1.4 },
      { code: 'AltLeft', label: 'Alt', width: 1.2 },
      { code: 'Space', label: 'Space', insertText: ' ', width: 7 },
      { code: 'AltRight', label: 'Alt', width: 1.2 },
      { code: 'ControlRight', label: 'Ctrl', width: 1.4 },
    ],
  ],
};
